name: Fontship
description: A font development toolkit and collaborative work flow
outputs:
  family-name:
    description: Font Family Name
  font-version:
    description: Font Version
  DISTDIR:
    description: Directory name with font family and detailed git version string
runs:
  using: docker
  image: docker://theleagueof/fontship:v0
  args:
    - make
    - _gha
    - dist
branding:
  icon: package
  color: green
