#!/usr/bin/env sh
set -e

: "${ARCHTAG:=20210207.0.15200}"

DESC=$(git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g')

: "${DOCKER_BUILDKIT:=1}"
export DOCKER_BUILDKIT

docker build \
	--build-arg ARCHTAG="$ARCHTAG" \
	--build-arg VCS_REF="${1:-$DESC}" \
	--tag "$IMAGE_NAME" \
	./
